apiVersion: v2
name: platform-helm-chart-metacontroller-operator-loki-rule-group
description: GlueOps Helm Chart to deploy the GlueOps Loki Rule Group Controller

appVersion: v0.1.0

version: 0.1.0-alpha13
