apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lokialertrulegroups.metacontroller.glueops.dev
spec:
  group: metacontroller.glueops.dev
  names:
    kind: LokiAlertRuleGroup
    listKind: LokiAlertRuleGroupList
    plural: lokialertrulegroups
    singular: lokialertrulegroup
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              rules:
                type: array
                items:
                  type: object
                  properties:
                    alert:
                      type: string
                    expr:
                      type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
          status:
            type: object
            properties:
              synced:
                type: string
    subresources:
     status: {}
