apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-alert-rule-group-controller
spec:
  replicas: {{ .Values.loki-alert-group-controller.replicaCount }}
  selector:
    matchLabels:
      app: loki-alert-rule-group-controller
  template:
    metadata:
      labels:
        app: loki-alert-rule-group-controller
    spec:
      containers:
      - name: loki-alert-rule-group-controller
        image: ghcr.io/glueops/metacontroller-operator-loki-rule-group:{{ .Values.loki-alert-group-controller.image.tag}}
        imagePullPolicy: {{ .Values.loki-alert-group-controller.image.pullPolicy }}
        env:
        - name: LOKI_GATEWAY_URL
          value: {{ .Values.loki-alert-group-controller.image.lokiGatewayUrl }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loki-alert-rule-group-controller
spec:
  selector:
    app: loki-alert-rule-group-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
