apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: {{ .Release.Name }}
spec:
  generateSelector: true
  parentResource:
    apiVersion: metacontroller.glueops.dev/v1alpha1
    resource: lokialertrulegroups
  childResources:
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ .Release.Name }}.{{ .Values.appNamespace }}
    finalize:
      webhook:
        url: http://{{ .Release.Name }}.{{ .Values.appNamespace }}/finalize
